apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./pvc.yaml
  - ../../../components/nodered

configMapGenerator:
  - name: nodered-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: nodered
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: nodered
        namespace: home-automation
      spec:
        valuesFrom:
        - kind: ConfigMap
          name: nodered-values
          valuesKey: values.yaml
