apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hosted
resources:
  - ../../../components/external-dns
  - ./external-dns-config.yaml

configMapGenerator:
  - name: external-dns-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: external-dns
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: external-dns-values
          valuesKey: values.yaml
