apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: frigate
      version: 7.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: flux-system
