apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: frigate
      version: 7.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: flux-system
