apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-app
  namespace: flux-system
spec:
  components:
  - ./values
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/components/keycloak
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
