apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows
resources:
  - ./oidc-secret.yaml
  - ./argo-workflows-admin-sa.yaml
  - ./argo-workflows-admin-crb.yaml
  - ./argo-workflows-admin-secret.yaml
  - ./user-default-login-sa.yaml
  - ./user-default-login-role.yaml
  - ./user-default-login-rb.yaml
  - ./user-default-login-secret.yaml
  - ../../../components/argo-workflows
  - ./artifact-repositories.yaml

configMapGenerator:
  - name: argo-workflows-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: argo-workflows
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: argo-workflows-values
          valuesKey: values.yaml
