apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: local-path-provisioner-app
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/components/local-path-provisioner
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
