# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/24

git:
  - repository: https://github.com/raelix/home-assistant.git
    track:
      - all

automation: 
script: 
scene: 
# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml