# cloud:
# config:
# frontend:
# history:
# logbook:
# map:
# mobile_app:
# person:
# script:
# ssdp:
# sun:
# system_health:
# updater:
# zerocon:

# Load frontend themes from the themes folder
# frontend:
#   themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/24


# automation:
# script:
# scene:
# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml
