apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./pvc.yaml
  - ./replication-source.yaml
  - ../../../components/home-assistant

configMapGenerator:
  - name: home-assistant-values
    files:
      - values.yaml=values.yaml
  # - name: home-assistant-configuration
  #   files:
  #     - ./configuration.yaml
  #   options:
  #     disableNameSuffixHash: true

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: home-assistant
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: home-assistant-values
          valuesKey: values.yaml
