apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-postgres-superuser
    namespace: hosted
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:C73nLUoMR/o=,iv:sTZQNM7eYmwmrvcTElhLRkeDDleflVm/HaEYzZP75xw=,tag:4oYN+ZN4jPMldVcFcrzEYw==,type:str]
    password: ENC[AES256_GCM,data:TGqX6aPkXqPvSOIK29gNlA==,iv:0DU/entpQd5p+r0ZRqCfBOMY5p0wdA7rUzJtuONEqy4=,tag:F5zZ8QyOFkKXOn/P+Ap38g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elje5gj3cyqhn44m66xlngczm8dklwmry9803ne69945e256xgequ9xtt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOXpzZ3YzcDVIaVBBcUlQ
            TEhuYitKd2FxTUdOWUxDbkR3R3FwRHpZelQ4CjVnTHd1V1ZUUG0vMkJRaTQwRXJz
            alAxQXZDcFA3Rmh6dmo4S2Ewd2JBcTgKLS0tIDZNKzV2eUVCU3ZkaUhTWFB6cVBr
            M2NWOElsdStXNk1YeWVYL0ZmZlNlL3MKDqlKZD7VKbCKcwD4qupRHBma2A5hh7zg
            CKC+eCivM2tw9C4GdkDrwFcAYr4nRZDYZ7W+RGSsg7EH32zJ/ygSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-22T15:12:56Z"
    mac: ENC[AES256_GCM,data:iMoS/9wQh3xGVod+q9XLRzPnSt96VKST1i7j6U1V6YHuTNbN3KX/N7xe/AIeKn/sCGGpPe27T7rv/7eBQ8XUU7tYZCyeVQacCCCL8i0Uk/ssJv5fIGZfAKiBGIDu8nAC6c1AzeQvWJNOEN2yjSFYB08MSoeogm0swr+W9VaQfuQ=,iv:qcFMvs5NHUEIRiiComGbFSlCAIuqju8UZMgn902PvuI=,tag:z54iIaZOa+5K/FEbNg51/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3