apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: coder
      owner: root
      secret:
        name: cloudnative-pg-postgres-superuser
  superuserSecret:
    name: cloudnative-pg-postgres-superuser