apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./pvc.yaml
  - ./ring-mqtt-options.yaml
  - ../../../components/ring-mqtt

configMapGenerator:
  - name: ring-mqtt-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: ring-mqtt
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: ring-mqtt-values
          valuesKey: values.yaml
