# Default values for compreface-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

postgres:
  repository: postgres
  pullPolicy: Always
  tag: 11.5
  db_name: frs
  db_port: 5432
  db_password: postgres
  db_user: postgres
  name: cf-db-data

core:
  repository: exadel/compreface-core
  pullPolicy: Always
  tag: 1.1.0
  port: 3000
  replicas: 1
  name: cf-core

api:
  repository: exadel/compreface-api
  pullPolicy: Always
  tag: 1.1.0
  port: 8080
  replicas: 1
  name: cf-api

admin:
  repository: exadel/compreface-admin
  pullPolicy: Always
  tag: 1.1.0
  port: 8080
  replicas: 1
  name: cf-admin

fe:
  repository: exadel/compreface-fe
  pullPolicy: Always
  tag: 1.1.0
  port: 80
  replicas: 1
  name: cf-fe


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "compreface"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.raelix.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.raelix.com/oauth2/start"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
  hosts:
    - host: &host "compreface.raelix.com"
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
  - hosts:
    - *host

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
