apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cloudnative-pg-app
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production/cloudnative-pg/app
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: cloudnative-pg-config
#   namespace: flux-system
# spec:
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/production/cloudnative-pg/config
#   prune: true
#   wait: true
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
#   dependsOn:
#     - name: cloudnative-pg-app
