apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hosted
resources:
  - ../../../components/portal

configMapGenerator:
  - name: portal-values
    files:
      - values.yaml=values.yaml
  - name: portal-configuration
    files:
      - ./config.yml
    options:
      disableNameSuffixHash: true

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: portal
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: portal-values
          valuesKey: values.yaml
