apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: hosted
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: 12.1.9
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
