apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: argo-workflows
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: 14.10.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
