apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/rancher/local-path-provisioner
  ref:
    branch: master
