apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./grafana-sso.yaml
  - ./scrape-config.yaml
  - ../../../components/kube-prometheus-stack

configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml=values.yaml
  - name: opensea-dashboard
    namespace: monitoring
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        k8s-sidecar-target-directory: "/tmp/dashboards/opensea-dashboard"
    files:
      - dashboards/opensea-dashboard.json


configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: kube-prometheus-stack-values
          valuesKey: values.yaml
