apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ha-backup
  namespace: home-automation
spec:
  sourcePVC: home-assistant-data
  trigger:
    schedule: "*/1 * * * *"
  rclone:
    rcloneConfigSection: "gdrive"
    rcloneDestPath: "rclone/ha-claim"
    rcloneConfig: "rclone-secret"
    copyMethod: Direct