apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
  # namespace: message
spec:
  image: emqx/emqx:5.0.13@sha256:9629ae26acce04ec0066682f49b5c03b90e86a552898a43ff00ce3f00de5b31d
  coreTemplate:
    spec:
      envFrom:
        - secretRef:
            name: dashboard-auth
      extraContainers:
      - name: users-creation
        image: centos:latest
        envFrom:
          - secretRef:
              name: dashboard-auth
        volumeMounts:
        - name: mqtt-users
          readOnly: true
          mountPath: "/etc/mqtt-users"
        command:
          - /bin/bash
          - -c
          - |
            echo "waiting web server to be ready"
            until $(curl --output /dev/null --silent --fail \
            -u $EMQX_DASHBOARD__DEFAULT_USERNAME:$EMQX_DASHBOARD__DEFAULT_PASSWORD \
            http://localhost:18083/api/v5/monitor_current); do
              printf '.'
              sleep 5
            done
            echo "creating users..."
            curl --output /dev/null --silent \
              -u $EMQX_DASHBOARD__DEFAULT_USERNAME:$EMQX_DASHBOARD__DEFAULT_PASSWORD \
              -X POST \
              -d @/etc/mqtt-users/users.json \
              'http://localhost:18083/api/v5/authentication/password_based%3Abuilt_in_database/users' \
              -H 'Content-Type: application/json'
            echo "done"
            sleep infinity
      extraVolumes:
        - name: mqtt-users
          secret:
            secretName: mqtt-users
  bootstrapConfig: |
    authentication {
      backend = "built_in_database"
      mechanism = "password_based"
      password_hash_algorithm {name = "sha256", salt_position = "suffix"}
      user_id_type = "username"
    }
    node {
      cookie = emqxsecretcookie
      data_dir = "data"
      etc_dir = "etc"
    }
