apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync-system
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: "0.11.x"
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
