apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hosted
resources:
  - ./minio-creds.yaml
  - ../../../components/minio

configMapGenerator:
  - name: minio-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: minio
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: minio-values
          valuesKey: values.yaml
