apiVersion: v1
data:
    root-password: ENC[AES256_GCM,data:AuNA5mU10bwIT9Cw,iv:pDrExjPk0sQFgnZ4hk+jPr9pBi2mzKMUAnI2NTNs68g=,tag:T3LWDpgpIS8uPYqZrhI5mg==,type:str]
    root-user: ENC[AES256_GCM,data:SSARpYree9I=,iv:rIPsyVdKZtTxR1piUoCF4uUFuo01N1XogftN9WIk0ec=,tag:OWK7ofDz/We55r+xEptdiw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: minio-creds
    namespace: hosted
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elje5gj3cyqhn44m66xlngczm8dklwmry9803ne69945e256xgequ9xtt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MFN3ODhSK2JNenJub1hY
            NGJWbGlhL2JiMXhaQlE5WUNWRUxXMlc1RVhFCnJqcnBSa003dW9nZFJuUE8zTzZa
            dXpQM0hzaEM3aSs0VjcwNmx0WC9qcEUKLS0tIDAzU3lQLzgwSnRaNW1GM3hGaTJr
            UEVoekJLUUszSktvVFVJamNpNytqdzgKyBZwOxkg8VIOoXpNavSeKG8W+Ds6ain3
            wH5f+ePLKVGXv7KMzOqcJlWyTxLZ08Te6XzzEqQiqEq58QhtZbZ1Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-28T06:27:28Z"
    mac: ENC[AES256_GCM,data:5i2whE5NkvXhlB8dJmuMyjiDxwyeHbSLlkL64E4o78Dhw0a9Lc4RWVywStQJLxUW4wArztKQdFhOnTtcQCfQ5VYBqklR/PR9JJmcsT4JXoIFDMWwR9COuSXXafIspB/O3qZcG8eqhzLs3sdLJ1HOot9p5QnHCKn9k3ib9RzVvj0=,iv:T2YqrjU9qFhZFNOdNEgMSCzmfCDn0dSZ9Nw1cKNemVI=,tag:yOnLD7sEgSiydriuzf1gWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3