apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: hosted
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: "2.1.4"
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system