apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy
resources:
  - ./oauth2-proxy.yaml
  - ../../../components/oauth2-proxy

configMapGenerator:
  - name: oauth2-proxy-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: oauth2-proxy
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: oauth2-proxy-values
          valuesKey: values.yaml
