config:
  clientID: "q0vB910C2dfzbvufYvwI7eAqWqq0mY8H"
  clientSecret: "x4yBKlNYZ8Nt6vUhVyu0pQaK1zkv0tDUrgsedg0IAR4yUgQW66a7Sc4FkpRFGjnt"
  cookieSecret: "NHY5UkJ2Ylplb1dMaThJMWM5TXB2NlA1SVY3dHhlTHM="
  configFile: |-
    provider = "oidc"
    provider_display_name = "Raelix HomeLab Login"
    oidc_issuer_url = "https://dev-tpkvv6pf614lnn28.us.auth0.com/"
    email_domains = [ "*" ]
    scope = "openid profile email"
    whitelist_domains = [".raelix.com"]
    pass_authorization_header = true
    pass_access_token = true
    pass_user_headers = true
    set_authorization_header = true
    set_xauthrequest = true
    cookie_refresh = "1m"
    cookie_expire = "30m"
    cookie_domains = [".raelix.com"]

ingress:
  enabled: true
  path: /
  pathType: ImplementationSpecific
  hosts:
    - oauth2-proxy.raelix.com
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - hosts:
        - oauth2-proxy.raelix.com