apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: compreface
  namespace: home-automation
spec:
  interval: 6h
  chart:
    spec:
      chart: ./helm-config
      sourceRef:
        kind: GitRepository
        name: compreface
        namespace: flux-system
      interval: 12h
