ignore: |
  .vscode/
  clusters/production/flux-system/
extends: default
rules:
  truthy:
    allowed-values: ["true", "false", "on"]
  document-start:
    present: false
  document-end:
    present: false
  comments:
    min-spaces-from-content: 1
  line-length: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation: false
