apiVersion: v1
kind: Secret
metadata:
    name: keycloak-auth
    namespace: keycloak
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:mUyLwZP3iWg=,iv:JaeX44bjdkNEebp6lzZNQyyi4aIT8PGUfTroQUniqGc=,tag:mozuGYX5n6lwb0GruBcnug==,type:str]
    management-password: ENC[AES256_GCM,data:utxVdhoFuMo=,iv:ZbaMRvXVAM63MdYNsAh5Hkcaohh9mh1oudxc1uJ40i4=,tag:gCIFyrL3xom7IN9okaimog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elje5gj3cyqhn44m66xlngczm8dklwmry9803ne69945e256xgequ9xtt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV0Q4eDh4SVZvMUtMdnpP
            cE9GSk82K3ZEbHVibGlYSDI1dDdkekhDYkVjCkZ5Z21Ca0tnT0czckg1ZW5qZnRI
            cGZUekpHanRjODdHSmttVWtqdEJlRHcKLS0tIGhKWVBwemZLS2haTEc5S1puYUl3
            WjFXWnFCRC91bUFpVi9OQUo1dmJzcncKb/HQZTMXMPNThUlMFx3mAPhUPhDBuSNG
            e97Qclx1a+UTrPyWQ4O3bfnbZT3Vn6IfZlBFb5HKAV2mUDpFw4vqvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-14T23:02:23Z"
    mac: ENC[AES256_GCM,data:92al/QS81Sqz4+VgM+sBrGtdXIuIYuTFnuIRy2CMOnCZ/Gy2JmZ6q8U6nOKOAFzrED36fz21n8NlAmO1XZJ2O7Q9fi+ORRNQtmcw2stJoXrz+VuVAvi1uhV8SSVhAua9+7HtT35VqGx8PWmUgezzQzlC08dn3sQFZ4r/ZaCyzjk=,iv:x7/9JNsdVNWPBEpqYzUaQspS1gSDlracCbkXn7HDlDw=,tag:gQYqZAsWaI3F+XUU3TV8Ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
