apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ./keycloak-auth.yaml
  - ./keycloak-postgresql-auth.yaml
  - ./cli-config.yaml
  - ../../../components/keycloak

configMapGenerator:
  - name: keycloak-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: keycloak
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: keycloak-values
          valuesKey: values.yaml
