apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hivemq
  namespace: hivemq
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 0.11.10
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: hivemq
        namespace: flux-system