apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hivemq
  namespace: hivemq
spec:
  interval: 30m
  chart:
    spec:
      chart: hivemq-operator
      version: 4.10.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: hivemq
        namespace: flux-system