apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: z2m-sensors-data
  namespace: home-automation
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  # storageClassName: ceph-block
