apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: z2m-sensors-backup
  namespace: home-automation
spec:
  sourcePVC: z2m-sensors-data
  trigger:
    schedule: "0 18 * * *"
  rclone:
    rcloneConfigSection: "gdrive"
    rcloneDestPath: "rclone/z2m-sensors"
    rcloneConfig: "rclone-secret"
    copyMethod: Direct
