apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql-auth
    namespace: keycloak
type: Opaque
data:
    password: ENC[AES256_GCM,data:LIoUqKDZ0FY=,iv:eS0quWo+amx7ChuZqTU2DHgPzWIS8+hJaSK1l1Fm+EA=,tag:7N3wGRzE51oWTVE6ZHIBNw==,type:str]
    postgres-password: ENC[AES256_GCM,data:G0LPr3K8EL0=,iv:1Yzn7xYX/UlZrkrNW5g4qzh8TyfpsW/BsiWn4DHi1AA=,tag:5VP5FRoYU12nGCbtQ1Ko2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elje5gj3cyqhn44m66xlngczm8dklwmry9803ne69945e256xgequ9xtt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcjRjbnZaVmd2OEJ3cjhp
            eFVROVFEQnJWU3haTjBMQWFLM3BBd1VmVjN3CjhvSTR6aUJuakRLZndIQk9ac1pZ
            QVVpUHo3cEE3YXFWalVFSjRBYkJYYmcKLS0tIGFiaVEyUjRtVXp6MG5sd1RHSGVy
            QnZ2ZlRTYWtSM0JhSkxKeGhQOFd3MlEKwFzI91abuP1jHEVIwbKcYhRWa4eY57ex
            Jbux7P9Fv+I6M9u6PcZs8QU0zjM6WopTHVjmHxdXJLdvJnkt3GvFAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-14T23:02:27Z"
    mac: ENC[AES256_GCM,data:c1rer0rIfnbTWcYWAie/R4WL7wlJHjvR1bsZbpiGVrXFD5+d2Y+3rYbL1Ixp9Jodt3XCUsw49MOfjicjEfz/2YSyo+YZniOZHOC8MIJWSU072a/I4iY6sp7qS9/Lgvu9VF2qXrj4XQowkS2VngkKqzAJQy9amwZiZg6So7taD4Y=,iv:a+w3hEF9Ov045U7CVZYHTOgyb4gLy9eJvg443VrdLuA=,tag:mnNKV419mABTk0HFmPpixg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
