apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: paperless-app
  namespace: flux-system
spec:
  dependsOn:
    - name: redis-app
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production/paperless/app
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
