apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: coder-app
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  dependsOn:
  - name: cloudnative-pg-app
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production/coder/app
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
 