apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-snapshotter-controller
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/kubernetes/snapshot-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
    namespace: flux-system
  targetNamespace: kube-system
  dependsOn:
    - name: external-snapshotter-crd
