apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-csi
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/kubernetes/csi-snapshotter
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
    namespace: flux-system
  targetNamespace: kube-system
  dependsOn:
    - name: external-snapshotter-crd
    - name: external-snapshotter-controller
