apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo
spec:
  interval: 30m
  chart:
    spec:
      chart: argo-workflows
      version: "0.41.1"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system