apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx-operator
  namespace: emqx-operator-system
spec:
  interval: 30m
  chart:
    spec:
      chart: emqx-operator
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system