apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emqx-operator-system
resources:
  - ../../../components/emqx-operator

configMapGenerator:
  - name: emqx-operator-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: emqx-operator
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: emqx-operator
        namespace: emqx-operator-system
      spec:
        valuesFrom:
        - kind: ConfigMap
          name: emqx-operator-values
          valuesKey: values.yaml
