apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./pvc.yaml
  # - ./replication-source.yaml
  - ../../../components/n8n

configMapGenerator:
  - name: n8n-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: n8n
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: n8n-values
          valuesKey: values.yaml
